name: Update IC versions file

on:
  schedule:
    - cron: "10 * * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  update-ic-versions-file:
    runs-on: ubuntu-latest
    environment: CREATE_PR
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: app-token
        with:
          app-id: ${{ vars.PR_CREATION_BOT_APP_ID }}
          private-key: ${{ secrets.PR_CREATION_BOT_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          token: ${{ steps.app-token.outputs.token }}

      - name: Update IC versions file
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          set -eEuxo pipefail

          time python ci/src/mainnet_revisions/mainnet_revisions.py subnets

  update-nervous-system-wasms:
    runs-on:
      labels: dind-small
    environment: CREATE_PR
    container:
      image: ghcr.io/dfinity/ic-build@sha256:994bfcba2fa5efbb52c515bb01e6e8a5828878d6528603e7133fb195bd2a6c89
      options: >-
        -e NODE_NAME --privileged --cgroupns host -v /cache:/cache -v /var/sysimage:/var/sysimage -v /var/tmp:/var/tmp -v /ceph-s3-info:/ceph-s3-info
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: app-token
        with:
          app-id: ${{ vars.PR_CREATION_BOT_APP_ID }}
          private-key: ${{ secrets.PR_CREATION_BOT_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup gh cli
        uses: ksivamuthu/actions-setup-gh-cli@c78dbed4be2f8d6133a14a9a597ee12fd4ed5c93 # v3
        with:
          version: 2.53.0

      - name: Update Mainnet canisters file
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          set -eEuxo pipefail

          # Leftover from previous step of setting up gh cli
          rm gh_tar

          time python ci/src/mainnet_revisions/mainnet_revisions.py canisters
